<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEf5zdsx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEf5zdsx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEf5zdsx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEf5zdsx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEf5zdsx\appProdProjectContainer([
    'container.build_hash' => 'Ef5zdsx',
    'container.build_id' => '45ab22a1',
    'container.build_time' => 1605130080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEf5zdsx');
